build:
  writeStats: true

taxonomies:
  authors: authors
  tags: tags
  categories: categories
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false
