google_adsense: ca-pub-7827859788508375

microsoft_clarity:
  id: jqz81bklca

hb:
  blog:
    giscus:
      repo: coding-pub/openmodels
      repo_id: R_kgDOLJ1aDA
      category: General
      category_id: DIC_kwDOLJ1aDM4CctHK
  docs:
    giscus:
      repo: coding-pub/openmodels
      repo_id: R_kgDOLJ1aDA
      category: General
      category_id: DIC_kwDOLJ1aDM4CctHK
