title: OpenModels
copyright: Copyright © 2022-2023 [OpenModels](https://openmodels.org). All Rights Reserved.
baseURL: https://openmodels.org/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
enableRobotsTXT: true

outputs:
  home:
    - DecapCMSConfig
    - HTML
    - Offline
    - SearchIndex
    - RSS
    - WebAppManifest

permalinks:
  blog: /blog/:year/:month/:title/
  news: /news/:year/:month/:title/

taxonomies:
  _merge: shallow

markup:
  _merge: deep

build:
  _merge: shallow

menus:
  _merge: deep

languages:
  _merge: deep

security:
  funcs:
    getenv:
      - '^HUGO_'
      - '^CI$'
      - '^GITHUB_TOKEN$'

ignoreErrors:
  - error-remote-getjson