main:
  - name: AI Tools
    identifier: icons
    weight: 10
    url: https://aitools.org.cn/
    params:
      icon:
        name: icons
        vendor: fas

  - name: AI Infra
    weight: 20
    url: https://ai-infra.ccom/
    params:
      icon:
        name: hugo
        vendor: simple
