imports:
  - path: github.com/hbstack/blog/modules/sidebar/profile
  - path: github.com/hugomods/video-js
  - path: github.com/hugomods/aos
  - path: github.com/hbstack/header/modules/banner
  - path: github.com/hugomods/site/common
